import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex justify-between items-center mx-auto text-black bg-slate-100 max-w-4xl'>
          <div className='flex justify-start'>
            <a className='font-medium p-2 m-2  text-md cursor-pointer hover:bg-slate-300 hover:rounded-md hover:font-semibold'>Home</a>
            <a className='font-medium p-2 m-2 transition-all  ease-in-out duration-100 text-md cursor-pointer hover:bg-slate-300 hover:rounded-md hover:font-semibold'>All</a>
            <a className='font-medium p-2 m-2 transition-all  ease-in-out duration-100 text-md cursor-pointer hover:bg-slate-300 hover:rounded-md hover:font-semibold'>Men</a>
            <a className='font-medium p-2 m-2 transition-all  ease-in-out duration-100 text-md cursor-pointer hover:bg-slate-300 hover:rounded-md hover:font-semibold'>Women</a>
          </div>
          <div className='p-2'>
            <input className='p-2 w-80 rounded-lg transition-all  ease-in-out duration-100'>
            </input>
          </div>
          <div className='flex justify-end'>
            <a className='font-medium p-2 m-2 transition-all  ease-in-out duration-100 text-md cursor-pointer hover:bg-slate-300 hover:rounded-md hover:font-semibold flex'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 mr-2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
              </svg>
              3
            </a>
          </div>

        </nav>
        {children}</body>
    </html>
  )
}
